fixed dbtest so it would give a better error than NoClassDefFoundError when it is unable to connect to the database
git-svn-id: https://source.jasig.org/uPortal/trunk@9967 f5dbab47-78f9-eb45-b975-e544023573eb